### ISSUE TITLE
iphone Chrome not showing.. 

### ISSUE THREAD

**Issue by RohanYoon** [h5p/h5p-speak-the-words#11]
Hi 

I am so sorry if I should update the issue here but I hope to get some help. 

I was trying to load voice recognition feature (speak the words) on Chrome from iphone but I am getting this error although I am using the chrome. 
https://prnt.sc/oe032q

The error page that I am trying to load is actually this page - https://h5p.org/speak-the-words

I have done factory reset for the phone and download the latest version Chrome (75.0.03770.103) 
I am using iphone 6 plus with software version 12.3.1. 
Is there anything I need to update on ios to make this work? Please render your expertise here. 

Thank you.

**Comment by thomasmars** [comment]
Hi,
Chrome on iOS has to use iOS UIWebView on iPhone for their browser rendering, which means that Chrome on iOS is basically just a wrapper around Safari. This means that it can only support features that Safari support.
Unfortunately the library we use for voice recognition is not supported yet by Safari, ref: https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API#SpeechRecognition

**Comment by RohanYoon** [comment]
Thank you so much for the explanation. 
1. sorry for my ignornace but it would be the same for Firefox in iOS? 
2. Do you have any idea or any way to submit such request to Safari to enable the Web Speech API? 

Thank you.

**Comment by thomasmars** [comment]
1) Yes
2) No, sorry I don't.
